config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user =User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_url
  end

  def show
    @user =User.find(params[:id])
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
    @user =User.find(params[:id])
    @user.update_attributes(user_params)
     redirect_to root_url
    
  end

  def destroy
    @user =User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end


  def user_params
    params.require(:user).permit(:name,:email,:password)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampleform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1><br><br><br>
<div>
<% @user.each do |f| %>
 <table class="table table-dark">


  <tbody>
         <thead>

    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Email</th>
      <th scope="col">Tabs</th>
    </tr>
  </thead>
    <tr>

      <th scope="row"><%= f.id %></th> 

      <td><%=f.name%></td>
      <td><%=f.email%></td>
      <td><%= link_to 'Show', user_path(f) %>
 <%= link_to 'Edit', edit_user_path(f)%>
  <%= link_to 'Destroy', user_path(f), method: :delete, data: {confirm:'Are you sure?'} %><br><br></td>
    </tr>
  </tbody>
</table>

 <% end %>
 <br><br><br>
 <%= link_to 'Enter New User', new_user_path %>

app/views/users/new.html.erb
<br><br><br><div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create A User</h1>
    <%= form_for @user do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br><br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<h1>User's Detailed Info</h1>
 <br><br>Name: <%= @user.name %><br><br>
 <br><br>Email: <%= @user.email %><br><br>
 <br><br>Created: <%= @user.created_at %><br><br>
 <br><br>Updated: <%= @user.updated_at %><br><br>
    
  </div>
</div>